import BoostrapBundle from "@/components/InstallBootstrap/BoostrapBundle";
import Navbar from "@/components/Navbar/Navbar";
import "@/theme/scss/bootstrap.scss"
import "@/theme/scss/styles.scss"
export const metadata = {
  title: "Intello",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <BoostrapBundle/>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
